In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits= load_digits()

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(digits.data,digits.target,test_size=0.3)

In [6]:
#Logistic Regression
lr= LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9638888888888889

In [11]:
# import seaborn as sns
# from sklearn.metrics import confusion_matrix
# y_pred = lr.predict(X_test)

# # Create confusion matrix
# cm = confusion_matrix(y_test, y_pred)

# # Plot confusion matrix
# plt.figure(figsize=(10, 7))
# sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=digits.target_names, yticklabels=digits.target_names)
# plt.xlabel('Predicted Labels')
# plt.ylabel('True Labels')
# plt.title('Confusion Matrix')
# plt.show()

In [13]:
#SVM
svm=SVC(gamma='auto')
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.3861111111111111

In [15]:
#Random Forest
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9694444444444444

In [16]:
# KFold cross validation
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf


KFold(n_splits=3, random_state=None, shuffle=False)

In [17]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [18]:
#Use KFold for our digits example
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [21]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [22]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [23]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [25]:
scores_rf

[0.9415692821368948, 0.9415692821368948, 0.9215358931552587]

In [27]:
# cross_val_score function
from sklearn.model_selection import cross_val_score
#Logistic regression model performance using cross_val_score
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [29]:
#svm model performance using cross_val_score
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [32]:
#random forest performance using cross_val_score
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3)

array([0.93989983, 0.94490818, 0.92654424])

In [33]:
#Parameter tunning using k fold cross validation
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8736809435133459

In [34]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9398913718187462

In [35]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9465735567970205

In [36]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9465797641216636

In [37]:
############EXercise##############################
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Load the iris dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Labels

# Initialize models
models = {
    "Logistic Regression": LogisticRegression(solver='liblinear', multi_class='ovr'),
    "SVM": SVC(gamma='auto'),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(n_estimators=100)
}

# Perform cross-validation and store scores
model_scores = {}
for model_name, model in models.items():
    # 5-Fold Cross Validation
    scores = cross_val_score(model, X, y, cv=5)  # 5-fold cross-validation
    model_scores[model_name] = scores.mean()  # Store the mean accuracy
    print(f"{model_name}: Mean Accuracy = {scores.mean():.4f}")

# Determine the best model
best_model = max(model_scores, key=model_scores.get)
print(f"\nBest Model: {best_model} with Mean Accuracy = {model_scores[best_model]:.4f}")


Logistic Regression: Mean Accuracy = 0.9600
SVM: Mean Accuracy = 0.9800
Decision Tree: Mean Accuracy = 0.9600
Random Forest: Mean Accuracy = 0.9600

Best Model: SVM with Mean Accuracy = 0.9800
